ui/ncurses: Remove unused 'cod' variable
When configured with --disable-debug, we get an unused variable warning:

  ui/ncurses/nc-cui.c: In function 'cui_device_remove':
  ui/ncurses/nc-cui.c:439:24: error: unused variable 'cod'
  cc1: all warnings being treated as errors

This change just removes the temporary variable.

Signed-off-by: Jeremy Kerr <jk@ozlabs.org>